
from openai import OpenAI
from utils.prompts import prompt_summarize

client = OpenAI(
    api_key = "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", 
    base_url = "https://openrouter.ai/api/v1"
)

instruction = """
You are given a question and a list of descriptions from clips of a video, generated by a large language model. 
You need to answer the question based on the descriptions and also return the most relevant clip id to the question. 

Output the answer in the format:
Clip: [clip_id]
Answer: [answer]
"""

def response(question, output_path): 
    with open(output_path, 'r') as f:
        descriptions = f.readlines()

    descriptions = [description.strip() for description in descriptions]

    prompt = "Question: " + question + "\n\n" + "Descriptions: " + "\n".join(descriptions) + "\n\n" + instruction
    # print(prompt)

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
    )
    return response.choices[0].message.content


def summarize(output_path):
    with open(output_path, 'r') as f:
        descriptions = f.readlines()

    prompt = "Descriptions: " + "\n".join(descriptions) + "\n\n" + prompt_summarize
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
    )
    return response.choices[0].message.content



if __name__ == "__main__":
    question = "Who is the perpetrator in the video?"
    output_path = "data/results/gym.json"
    # print(response(question, output_path))
    print(summarize(output_path))