prompt_violence_detection = """
You are given a 15-second video clip. You task is to detect violence and describe the characters' behavior in the video.

Violence Reporting Rules:
1. If you observe ANY violent behavior, threats, or criminal activity, you MUST add a sentence starting with "WARNING: " followed by a detailed description. Place this as the FIRST element in your output list.
2. When reporting violence, be specific: describe who is involved, what weapon or action is used, what is being demanded or threatened, and the context.

Then, you need to describe the characters' behavior in the video, including characters' appearance, actions, movements, and spoken dialogue. No need to describe the contextual information. 

Requirements: 
1. Use a short descriptive phrase to refer to each character (eg. "the man in the blue shirt" or "a woman in the red dress", or just "a man" or "the woman").
2. Do not use "he," "she," "they," pronouns, or invented Names.
3. Each line must express one event/detail in a single sentence; split the sentence if needed.
4. Output English only.
5. Output a Python list of sentences. 
6. **Do NOT repeat the same information. Each sentence must describe a NEW event, action, or detail that has not been mentioned before.**

Output Format: 
Return the result as a Python list. Each element in the list should be a single sentence. Be concise. 
Example: ["WARNING: Description of the violent behavior", "Sentence 1 describing the characters' behavior", "Sentence 2 describing the characters' behavior", ...]

Checklist:
- [] Generate a python list. 
- [] No duplicate or near-duplicate sentences.
- [] Each element is a single sentence.
- [] Less than or equal to 10 sentences.
"""

# 2. If you observe suspicious behavior that MIGHT indicate violence (e.g., someone reaching for something, aggressive postures, threatening gestures, demands that seem coercive), add a sentence starting with "SUSPECTED: " followed by the description.
# 4. If there is already a WARNING message, do not generate a SUSPECTED message.
# Please only return the valid python list (which starts with "[" and ends with "]"), without any additional explanation or formatting.
# Example: ["WARNING: Description of the violent behavior", "Sentence 1 describing the characters' behavior", "Sentence 2 describing the characters' behavior", ...]



prompt_falling_detection = """
You are given a 15-second video clip. You task is to detect falling-down and describe the characters' behavior in the video.

Falling-down Reporting Rules:
1. If you observe someone falls down, you MUST add a sentence starting with "WARNING: " followed by a detailed description. Place this as the FIRST element in your output list.
2. When reporting falling-down, be specific: describe who fell down, what was the reason for falling-down, and the context.
3. Do not report the following as falling-down: intentional sitting, lying down, controlled movements like kneeling, squatting etc. only report the unexpected falling-down. 

Then, you need to describe the characters' behavior in the video, including characters' appearance, actions, movements, and spoken dialogue. No need to describe the contextual information. 

Requirements: 
1. Use a short descriptive phrase to refer to each character (eg. "the man in the blue shirt" or "a woman in the red dress", or just "a man" or "the woman").
2. Do not use "he," "she," "they," pronouns, or invented Names.
3. Each line must express one event/detail in a single sentence; split the sentence if needed.
4. Output English only.
5. Output a Python list of sentences. 
6. **Do NOT repeat the same information. Each sentence must describe a NEW event, action, or detail that has not been mentioned before.**
7. If there is no falling-down in the video, just generate the normal behavior descriptions.

Output Format: 
Return the result as a Python list. Each element in the list should be a single sentence. Be concise. 
Example: ["WARNING: Description of the falling-down", "Sentence 1 describing the characters' behavior", "Sentence 2 describing the characters' behavior", ...]

Checklist:
- [] Generate a python list. 
- [] No duplicate or near-duplicate sentences.
- [] Each element is a single sentence.
- [] Less than or equal to 10 sentences.
"""


prompt_summarize = """
You are given a question and a list of descriptions from clips of a video, generated by a large language model. 
You need to generate a summary as a whole video in one paragraph in one paragraph. Do not generate the information clip by clip. Solve the conflict information.  
"""


prompt_generate_full_memory = """
You are given a video along with a set of character features. Each feature is either:
• Face: a single video frame with a bounding box, or
• Voice: one or more speech segments, each containing start_time (MM:SS), end_time (MM:SS) and asr (transcript).
Every feature has a unique ID enclosed in angle brackets (e.g. <face_1>, <voice_2>).

Your Tasks (produce both in the same response) :

1. **Episodic Memory** (the ordered list of atomic captions)
• Using the provided feature IDs, generate a detailed and cohesive description of the current video clip. The description should capture the complete set of observable and inferable events in the clip. Your output should incorporate the following categories (but is not limited to them):
	(a)	Characters' Appearance: Describe the characters' appearance, such as their clothing, facial features, or any distinguishing characteristics.
	(b)	Characters' Actions & Movements: Describe specific gesture, movement, or interaction performed by the characters.
	(c)	Characters' Spoken Dialogue: Quote—or, if necessary, summarize—what are spoken by the characters.
	(d)	Characters' Contextual Behavior: Describe the characters' roles in the scene or their interaction with other characters, focusing on their behavior, emotional state, or relationships.

2. **Semantic Memory** (the ordered list of high-level thinking conclusions)
• Produce concise, high-level reasoning-based conclusions across five categories:
	(a) Equivalence Identification – Identify which face and voice features refer to the same character. Use the exact format: Equivalence: <face_x>, <voice_y>. Include as many confident matches as possible.
	(b) Character-level Attributes – Infer abstract attributes for each character, such as: Name (if explicitly stated), Personality (e.g., confident, nervous), Role/profession (e.g., host, newcomer), Interests or background (when inferable), istinctive behaviors or traits (e.g., speaks formally, fidgets). Avoid restating visual facts—focus on identity construction.
	(c) Interpersonal Relationships & Dynamics – Describe the relationships and interactions between characters: Roles (e.g., host-guest, leader-subordinate), Emotions or tone (e.g., respect, tension), Power dynamics (e.g., who leads), Evidence of cooperation, exclusion, conflict, etc.
	(d) Video-level Plot Understanding – Summarize the scene-level narrative, such as: Main event or theme, Narrative arc or sequence (e.g., intro → discussion → reaction), Overall tone (e.g., formal, tense), Cause-effect or group dynamics.
	(e) Contextual & General Knowledge – Include general knowledge that can be learned from the video, such as: Likely setting or genre (e.g., corporate meeting, game show), Cultural/procedural norms, Real-world knowledge (e.g., "Alice market is pet-friendly"), Common-sense or format conventions.

Strict Requirements (apply to both sections unless noted)

1. If a character has a provided feature ID, refer to that character only with the ID (e.g. <face_1>, <voice_2>).
2. If no ID exists, use a short descriptive phrase (e.g. “a man in a blue shirt”).
3. Do not use “he,” “she,” “they,” pronouns, or invented Names.
4. Keep face/voice IDs consistent throughout.
5. Describe only what is grounded in the video or obviously inferable.
6. Include natural Time & Location cues and setting hints when inferable.
7. Each Episodic Memory line must express one event/detail; split sentences if needed.
8. Output English only.
9. Output a Python list of sentences for each memory type.

Additional Rules for Episodic Memory

1. Do not mix unrelated aspects in one memory sentence.
2. Focus on appearance, actions/movements, spoken dialogue (quote or summary), contextual behavior.

Additional Rules for Semantic Memory

1. For Equivalence lines, use the exact format: Equivalence: <face_x>, <voice_y>.
2. Do not repeat simple surface observations already in the captions.
3. Provide only final conclusions, not reasoning steps.

Expected Output Format

Return the result as a single Python dict containing exactly two keys:

{
  "episodic_memory": [
    "In the bright conference room, <face_1> enters confidently, giving a professional appearance as he approaches <face_2> to shake hands.",
	"<face_1> wears a black suit with a white shirt and tie. He has short black hair and wears glasses.",
	"<face_2>, dressed in a striking red dress with long brown hair.",
	"<face_2> smiles warmly and greets <face_1>. She then sits down at the table beside him, glancing at her phone briefly while occasionally looking up.",
	"<voice_1> speaks to the group, 'Good afternoon, everyone. Let's begin the meeting.' His voice commands attention as the room quiets, and all eyes turn to him.",
	"<face_2> listens attentively to <voice_1>'s words, nodding in agreement while still occasionally checking her phone. The atmosphere is professional, with the participants settling into their roles for the meeting.",
	"<face_1> adjusts his tie and begins discussing the agenda, engaging the participants in a productive conversation."
  ],
  "semantic_memory": [
    "Equivalence: <face_1>, <voice_1>",
	"<face_1>'s name is David.",
	"<face_1> holds a position of authority, likely as the meeting's organizer or a senior executive.",
    "<face_2> shows social awareness and diplomacy, possibly indicating experience in public or client-facing roles.",
    "<face_1> demonstrates control and composure, suggesting a high level of professionalism and confidence under pressure.",
    "The interaction between <face_1> and <face_2> suggests a working relationship built on mutual respect.",
    "The overall tone of the meeting is structured and goal-oriented, indicating it is part of a larger organizational workflow."
  ]
}

Please only return the valid python dict (which starts with "{" and ends with "}") containing two string lists in "episodic_memory" and "semantic_memory", without any additional explanation or formatting.
"""